name: Deploy YOLO via GCP Workload Identity

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to VM via gcloud ssh
        run: |
          gcloud compute ssh instance-20260617-184557 \
            --zone=asia-east1-a \
            --project=project-d9243352-39fe-44a5-90d \
            --command="
              if [ ! -d 'DATN' ]; then
                git clone https://github.com/Paxx2303/DATN.git
                cd DATN
              else
                cd DATN
                git pull origin main
              fi
            "
